SELECT * FROM DUAL



SELECT pm.*,  (TO_CHAR(SYSDATE-3, 'yyyy-mm-dd') || ' 05:19:00') as timestamp2, 'XXXXXXXXXXXXXXXXXXXXX' as filler FROM STEVEN.POL_MEMO pm WHERE upddate >  TO_DATE(TO_CHAR(SYSDATE-3, 'yyyy-mm-dd') || '05:19:19', 'yyyy-mm-dd hh24:mi:ss');



CREATE TABLE STEVEN.TIMEZONE_POC (
	id NUMBER(20) PRIMARY KEY,
	CREATE_DATE TIMESTAMP,
	UPDATE_DATE TIMESTAMP,
	UPDATED_BY VARCHAR(30)
	
	
);
SELECT * from STEVEN.TIMEZONE_POC;
INSERT INTO STEVEN.TIMEZONE_POC VALUES(1, '2017-10-30 12:45:30', '2017-10-31 12:50:35',  'user1');

INSERT INTO STEVEN.TIMEZONE_POC VALUES(2, SYSDATE, SYSDATE+1,  'user1');
DELETE from STEVEN.TIMEZONE_POC WHERE id = 6;
commit;
DROP TABLE  TIMEZONE_POC